api:
  overview: 
    url: "https://euclinicaltrials.eu/ctis-public-api/search"
    payload:
      pagination:
        page: 1
        size: 100
      sort:
        property: "decisionDate"
        direction: "DESC"
      searchCriteria:
        containAll: null
        containAny: null
        containNot: null
        title: null
        number: null
        status: null
        medicalCondition: null
        sponsor: null
        endPoint: null
        productName: null
        productRole: null
        populationType: null
        orphanDesignation: null
        msc: null
        ageGroupCode: null
        therapeuticAreaCode: null
        trialPhaseCode: null
        sponsorTypeCode: null
        gender: null
        protocolCode: null
        rareDisease: null
        pip: null
        haveOrphanDesignation: null
        hasStudyResults: null
        hasClinicalStudyReport: null
        isLowIntervention: null
        hasSeriousBreach: null
        hasUnexpectedEvent: null
        hasUrgentSafetyMeasure: null
        isTransitioned: null
        eudraCtCode: null
        trialRegion: null
        vulnerablePopulation: null
        mscStatus: null
    headers:
      User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0"
      Accept: "application/json, text/plain, */*"
      Accept-Language: "en-US,en;q=0.5"
      Accept-Encoding: "gzip, deflate, br, zstd"
      Content-Type: "application/json"
      Origin: "https://euclinicaltrials.eu"
      Connection: "keep-alive"
      Referer: "https://euclinicaltrials.eu/ctis-public/search?lang=en"
      Cookie: "accepted_cookie=true"
      Sec-Fetch-Dest: "empty"
      Sec-Fetch-Mode: "cors"
      Sec-Fetch-Site: "same-origin"
      DNT: "1"
      Sec-GPC: "1"
      TE: "trailers"
