environment: "prod" # dev or prod
api:
  overview: 
    payload:
      pagination:
        page: 1
        size: 100
      sort:
        property: "decisionDate"
        direction: "DESC"
      searchCriteria:
        containAll: null
        containAny: null
        containNot: null
        title: null
        number: null
        status: null
        medicalCondition: null
        sponsor: null
        endPoint: null
        productName: null
        productRole: null
        populationType: null
        orphanDesignation: null
        msc: null
        ageGroupCode: null
        therapeuticAreaCode: null
        trialPhaseCode: null
        sponsorTypeCode: null
        gender: null
        protocolCode: null
        rareDisease: null
        pip: null
        haveOrphanDesignation: null
        hasStudyResults: null
        hasClinicalStudyReport: null
        isLowIntervention: null
        hasSeriousBreach: null
        hasUnexpectedEvent: null
        hasUrgentSafetyMeasure: null
        isTransitioned: null
        eudraCtCode: null
        trialRegion: null
        vulnerablePopulation: null
        mscStatus: null
  geocoding:
    headers:
      User-Agent": "ctis-scraper 1.0"

